# Generated by Django 3.2.17 on 2023-07-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor_StaffOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Professor_StaffOrderFile')),
            ],
            options={
                'verbose_name': 'GoverningBodyOrderFile',
                'verbose_name_plural': 'GoverningBodyOrderFiles',
            },
        ),
        migrations.RenameModel(
            old_name='GoverningBodyMembers',
            new_name='Professor_Staff',
        ),
        migrations.DeleteModel(
            name='GoverningBodyOrderFile',
        ),
        migrations.AlterModelOptions(
            name='professor_staff',
            options={'verbose_name_plural': 'Professor_Staff'},
        ),
        migrations.RemoveField(
            model_name='antiraggingcommittee',
            name='email',
        ),
        migrations.AddField(
            model_name='antiraggingcommittee',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
