# Generated by Django 3.2.17 on 2023-07-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicConsultancy',
        ),
        migrations.DeleteModel(
            name='AcademicPartnerShip',
        ),
        migrations.DeleteModel(
            name='FundedProjects',
        ),
        migrations.AlterField(
            model_name='conference',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None'), ('administrative_staff', 'Administrative Staff'), ('wardens', 'Wardens '), ('supporting_staff', 'Supporting Staff'), ('security_staff', 'Security Staff')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='facultystudentpublications',
            name='dep',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], max_length=100, verbose_name='Department of Faculty/student'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('All', 'All')], default='None', max_length=200),
        ),
        migrations.DeleteModel(
            name='ResearchGuides',
        ),
    ]
