# Generated by Django 3.2.17 on 2023-07-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        ('placements', '0005_achivements'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.faculty')),
            ],
        ),
    ]
