# Generated by Django 3.2.17 on 2023-07-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutCCE', '0004_management_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreaboutcce',
            options={'verbose_name_plural': 'More About CEC'},
        ),
    ]
