# Generated by Django 3.2.17 on 2023-07-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0027_remove_professionalbodiesteammembers_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllb', models.FileField(upload_to='SyllabusEE')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Syllabus EE',
            },
        ),
    ]
