# Generated by Django 3.2.17 on 2023-07-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0028_syllabusee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associationsevents',
            name='assosiation',
        ),
        migrations.RemoveField(
            model_name='associationteammembers',
            name='assosiation',
        ),
        migrations.RemoveField(
            model_name='professionalbodiesevents',
            name='ProfessionalBodies',
        ),
        migrations.RemoveField(
            model_name='professionalbodiesteammembers',
            name='ProfessionalBodies',
        ),
        migrations.AlterField(
            model_name='achivements',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='depabout',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='dephero',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='depupdates',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='handouts',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='laboratories',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsletters',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='objectives',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='poes',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='pos',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='psos',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='syllabuspdfs',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='vission',
            name='department',
            field=models.CharField(choices=[('EE', 'EE'), ('None', 'None')], default='None', max_length=200),
        ),
        migrations.DeleteModel(
            name='Associations',
        ),
        migrations.DeleteModel(
            name='AssociationsEvents',
        ),
        migrations.DeleteModel(
            name='AssociationTeamMembers',
        ),
        migrations.DeleteModel(
            name='ProfessionalBodies',
        ),
        migrations.DeleteModel(
            name='ProfessionalBodiesEvents',
        ),
        migrations.DeleteModel(
            name='ProfessionalBodiesTeamMembers',
        ),
    ]
